INSERT INTO page_view_data.raw_clicks(click_epoch, UTC_offset, request_url, user_agent, visitor_id, coords)
values(1666534120000, -4, 'https://request.com/something/', 'a b c d','123','{}');

INSERT INTO page_view_data.raw_clicks(click_epoch, UTC_offset, request_url, user_agent, visitor_id, coords)
values(1666620520000, 0, 'https://request.com/something/', 'a b c d','456','{}');

INSERT INTO page_view_data.raw_clicks(click_epoch, UTC_offset, request_url, user_agent, visitor_id, coords)
values(1666447720000, 1, 'https://request.com/something/', 'a b c d','789','{}');
